version: '3.8'
services:
  openldap:
    image: noi1031/openldap:2.5.14-debian11
    restart: always
    environment:
      LDAP_BASE_DN: dc=noise,dc=com
      LDAP_BASE_ROOT_DN: cn=admin,dc=noise,dc=com
      LDAP_BASE_ROOT_DN_PWD: admin.123
    ports:
      - 389:389
    volumes:
      - ./openldap-data:/usr/local/var/openldap-data
      - ./slapd.d:/usr/local/etc/openldap/slapd.d
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  phpldapadmin:
    image: osixia/phpldapadmin:stable-amd64
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - 8888:80
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
