---
version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.43.1
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.config.file=/etc/prometheus/web-config.yaml"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    restart: always
    network_mode: host
    # ports:
    #   - 9090:9090
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
