groups:
  - name: 主机内存告警规则组
    rules:
      - alert: "主机内存使用率高"
        # 计算内存使用率，大于等于 90% 并持续 2m 时告警
        expr: (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100) * on(instance) group_left(nodename) node_uname_info{}) >= 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "主机内存使用率持续 2m 高于 90% (instance : {{ $labels.instance }})"
          description: "主机内存使用率持续 2m 超过 90%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机内存页错误次数高"
        # 计算 1m 内产生的内存页错误次数，大于等于 1000 并且持续 2m 时告警
        expr: (rate(node_vmstat_pgmajfault[1m]) >= 1000) * on(instance) group_left (nodename) node_uname_info{}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "主机内存页错误次数升高 (instance {{ $labels.instance }})"
          description: "1m 内主机内存页错误次数升高大于 1000 次并持续 2m。通常是因为主机内存压力较大，有程序频繁读写、分配、回收内存导致"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机swap空间使用率高"
        # 计算 swap 空间使用率，大于等于 90% 并持续 2m 时告警
        expr: (((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100) * on(instance) group_left(nodename) node_uname_info{}) >= 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "主机 swap 空间使用率持续 2m 高于 90% (instance : {{ $labels.instance }})"
          description: "主机 swap 空间使用率持续 2m 高于 90%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机发生OOMKill事件"
        # 计算一分钟内 OOMKill 事件增加次数，大于 0 时告警
        expr: (increase(node_vmstat_oom_kill[1m]) * on(instance) group_left(nodename) node_uname_info) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "主机 1m 内发生的 OOMKill 事件大于 0 (instance : {{ $labels.instance }})"
          description: "主机 1m 内发生的 OOMKill 事件大于 0"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
  - name: 主机cpu告警规则组
    rules:
      - alert: "主机cpu使用率高"
        # 计算 5m 内 cpu 使用率，大于等于 90% 并持续 1m 时告警
        expr: (100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100) * on(instance) group_left(nodename, job) node_uname_info{})) >= 90
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "主机整体 cpu 使用率 5m 内高于 90% (instance {{ $labels.instance }})"
          description: "主机整体 cpu 使用率 5m 内高于 90%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机iowait使用率高"
        # 计算 5m 内 cpu iowait 使用率，大于等于 10% 并持续 1m 时告警
        expr: avg by(instance)(rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 >= 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "主机 cpu iowait 使用率 5m 内高于 10% (instance {{ $labels.instance }})"
          description: "主机 cpu iowait 使用率 5m 内高于 10%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机cpuSteal使用率高"
        # 计算 5m 内 cpu steal 使用率，大于等于 10% 并持续 1m 时告警
        expr: avg by(instance)(rate(node_cpu_seconds_total{mode="steal"}[5m])) * 100 >= 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "主机 cpu steal 使用率 5m 内高于 10% (instance {{ $labels.instance }})"
          description: "主机 cpu steal 使用率 5m 内高于 10%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
  - name: 主机磁盘告警规则组
    rules:
      - alert: "主机文件系统block空间使用率高"
        # 计算文件系统 block 空间使用率，大于等于 90% 并持续 5m 时告警
        expr: (ceil((node_filesystem_size_bytes{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*",mountpoint !~".*(pod|docker).*"}-node_filesystem_free_bytes{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*",mountpoint !~".*(pod|docker).*"}) *100/(node_filesystem_avail_bytes {fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*",mountpoint !~".*(pod|docker).*"}+(node_filesystem_size_bytes{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*",mountpoint !~".*(pod|docker).*"}-node_filesystem_free_bytes{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*",mountpoint !~".*(pod|docker).*"}))) * on(instance) group_left(nodename) node_uname_info{}) >= 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "主机文件系统 block 空间使用率持续 5m 高于 90% (instance {{ $labels.instance }})"
          description: "主机文件系统 block 空间使用率持续 5m 高于 90%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "主机文件系统inode空间使用率高"
        # 计算文件系统 inode 空间使用率，大于等于 90% 并持续 5m 时告警
        expr: ((ceil(((node_filesystem_files{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*", mountpoint!~"/boot.*"} - node_filesystem_files_free{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*", mountpoint!~"/boot.*"}) / node_filesystem_files{fstype=~"xfs|ext[0-9]+|nfs.*|ceph.*|gluster.*|[smbSMB].*", mountpoint!~"/boot.*"}) * 100)) * on(instance) group_left(nodename) node_uname_info{}) >= 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "主机文件系统 inode 空间使用率持续 5m 高于 90% (instance {{ $labels.instance }})"
          description: "主机文件系统 inode 空间使用率持续 5m 高于 90%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
      - alert: "磁盘io(IOutil)使用率高"
        # 计算磁盘 io 使用率，大于等于 50% 并持续 5m 时告警
        expr: ((rate(node_disk_io_time_seconds_total{device!~"dm-[0-9]+"}[1m]) * 100) * on(instance) group_left(nodename) node_uname_info{}) >= 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "主机磁盘 io ( IOutil ) 使用率持续 5m 高于 50% (instance {{ $labels.instance }})"
          description: "主机磁盘 io ( IOutil ) 使用率持续 5m 高于 50%"
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
