version: '3.8'
services:
  kuboard:
    image: eipwork/kuboard:v3
    restart: always
    environment:
      # 修改为 kuboard 的通信地址
      - KUBOARD_ENDPOINT=http://kuboard主机的IP地址:80
      - KUBOARD_AGENT_SERVER_TCP_PORT=10081
    ports:
      - 80:80/tcp
      - 10081:10081/tcp
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime

# docker run -d \
#   --restart=unless-stopped \
#   --name=kuboard \
#   -p 80:80/tcp \
#   -p 10081:10081/tcp \
#   -e KUBOARD_ENDPOINT="http://内网IP:80" \
#   -e KUBOARD_AGENT_SERVER_TCP_PORT="10081" \
#   -v /root/kuboard-data:/data \
#   eipwork/kuboard:v3
